import { Arguments } from 'yargs';

export interface BuildRunOptions extends Arguments {
  platform: 'ios' | 'android';
  config: string;
}

type ConfigIOS = {
  /** The workspace to build. */
  workspace?: string;
  /** The scheme to build. */
  scheme?: string;
  /** Overrides the `xcodebuild` command making the workspace & scheme options obselete. */
  buildCommand?: string;
  /** Path to the .app that will get generated by a custom build command. Ignored when not using a custom build command. */
  binaryPath?: string;
  /** Passes the quiet flag to `xcodebuild`. Does not print any output except for warnings and errors. */
  quiet?: boolean;
  /** The name of the simulator you would like to run tests on. Can be either the name or the id of the device. */
  device: string;
};

type ConfigAndroid = {
  /** The package name of your Android app. See Manifest.xml. */
  packageName: string;
  /** Overrides the `assembleDebug` gradle command. Should build the apk. */
  buildCommand?: string;
  /** Path to the .apk that will get generated by a custom build command. Ignored when not using a custom build command. */
  binaryPath?: string;
  /** Passes the quiet flag to `gradlew`. */
  quiet?: boolean;
};

export type Config = {
  ios?: ConfigIOS;
  android?: ConfigAndroid;
  /** Prevents the CLI/library from printing any logs/output. */
  debug?: boolean;
};

export type Logger = {
  info: (message?: any, ...optionalParams: any[]) => void;
  warn: (message?: any, ...optionalParams: any[]) => void;
  error: (message?: any, ...optionalParams: any[]) => void;
};
